ALTER TABLE "Service"
ADD COLUMN "bannerFocusX" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN "bannerFocusY" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN "bannerArtworkTitle" TEXT,
ADD COLUMN "bannerArtworkAuthor" TEXT,
ADD COLUMN "bannerArtworkNote" TEXT;
