ALTER TABLE "PaymentTransaction"
  ADD COLUMN "taxRate" INTEGER NOT NULL DEFAULT 4,
  ADD COLUMN "processingFee" DECIMAL(10,2);

ALTER TABLE "Settlement"
  ADD COLUMN "processingFeeAmt" DECIMAL(12,2) NOT NULL DEFAULT 0;

ALTER TABLE "SettlementItem"
  ADD COLUMN "commissionPct" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "processingFeeAmt" DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN "netAmount" DECIMAL(10,2) NOT NULL DEFAULT 0;
